name: Deploy to Production server

on:
  push:
    branches:
    - master

jobs:
  deploy:
    env:
      CI: false

    name: Deploy build files to server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Installing dependencies
      run: npm install
    
    - name: Building Angular Files
      run: |
        
        npm run build
        
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: islamic.nvinfobase.com
        username: develop
        KEY: ${{ secrets.KEY }}
        port: 7872
        source: "dist/admin-example/*"
        target: /var/www/html/islamicapp
        rm: true
        strip_components: 1
